he0119/CoolQBot

src/coolqbot/config.py
src/coolqbot/recorder.py
src/plugins/basic.py
src/plugins/gate.py
src/plugins/repeat.py

添加了测试群号，修改了复读群号的识别方式。修改了提问身份的功能。

add test group

---

src/plugins/ban.py
src/plugins/repeat.py

Add ban plugin

---

src/plugins/basic.py
src/plugins/recorder.py
src/plugins/status.py

Add hello message

---

azure-pipelines.yml

Try new pipelines 

---

src/bot.ini.example
src/coolqbot/config.py
src/plugins/robot/__init__.py
src/plugins/robot/qingyunke.py
src/plugins/robot/tuling.py

Add tuling api

---

src/plugins/fflogs/data.py

修复无法提示找不到数据，并加上更多昵称

---

CHANGELOG.md
Dockerfile
requirements.txt
src/plugins/fflogs/__init__.py
src/plugins/fflogs/api.py
src/plugins/fflogs/data.py
src/plugins/fflogs/exceptions.py

fflogs update

---

src/plugins/fflogs/__init__.py
src/plugins/fflogs/api.py
src/plugins/fflogs/data.py
src/plugins/fflogs/exceptions.py

给代码添加上类型标注

---

CHANGELOG.md
src/plugins/fflogs/__init__.py

FFLogs 插件更新

---

src/plugins/ff14/config.py
src/plugins/ff14/news.py

improve(ff14): 使用新闻发布日期作为推送判定标准

---

src/plugins/repeat/repeat_rule.py

change(repeat): 调整复读规则

---

poetry.lock
pyproject.toml
src/plugins/robot/config.py
src/plugins/robot/tencent.py

fix(robot): 更新至腾讯自然语言处理 API

---

Dockerfile
bot.py
poetry.lock
pyproject.toml
src/plugins/ff14/news.py
src/plugins/morning/__init__.py
src/plugins/pcr/calender.py
src/plugins/pcr/news.py
src/plugins/repeat/rank.py
src/utils/helpers.py

change!: 升级至 nonebot2 a14

---

src/web/nonebot_hk_reporter/__init__.py
src/web/nonebot_hk_reporter/platform/arknights.py
src/web/nonebot_hk_reporter/platform/bilibili.py
src/web/nonebot_hk_reporter/platform/ncm_artist.py
src/web/nonebot_hk_reporter/platform/platform.py
src/web/nonebot_hk_reporter/platform/weibo.py
src/web/nonebot_hk_reporter/post.py
src/web/nonebot_hk_reporter/scheduler.py
src/web/nonebot_hk_reporter/utils.py

- 使用最新的 [nonebot-hk-reporter](https://github.com/he0119/nonebot-hk-reporter/tree/025ae87602d48870b44f117dd020766d67736f96)
- 降低微博与B站的检查频率
- 添加网站无法访问时的提示

improve(sub): 升级 nonebot-hk-reporter 版本

---

Dockerfile

build: 调整 docker 镜像

---

poetry.lock
pyproject.toml
src/plugins/ff14/__init__.py
tests/plugins/ff14/test_price.py

支持 `/查价 萨维奈舞裙`，将默认在猫小胖区查询。
同时支持用户设置自己的默认值。

feat(ff14): 查价支持设置默认值

---

poetry.lock
pyproject.toml

feat: 更新至 nonebot2 b3

---

src/plugins/robot/__init__.py
src/plugins/robot/tencent.py

change(robot): 使用 rule 来跳过命令

---

Dockerfile

fix: 修复容器内字体问题

---

src/plugins/repeat/__init__.py
src/plugins/repeat/history.py
src/plugins/repeat/rank.py
src/plugins/repeat/recorder.py
tests/plugins/repeat/test_history.py
tests/plugins/repeat/test_rank.py

fix(repeat): 修复排行榜与历史排行榜报错的问题

---

poetry.lock
pyproject.toml

feat: 适配 NoneBot2 RC1

---

.github/workflows/main.yml
Dockerfile
gunicorn.conf.py
poetry.lock
pyproject.toml

feat: 升级 bison 版本至 0.6.0

---

bot.py
src/plugins/hospital/__init__.py
src/plugins/hospital/data_source.py
src/plugins/hospital/model.py
src/utils/helpers.py

feat: 增加赛博医院功能

---

.vscode/settings.json
src/plugins/hospital/__init__.py
tests/fake.py
tests/plugins/hospital/test_admit.py
tests/plugins/hospital/test_discharge.py
tests/plugins/hospital/test_rounds.py

feat(hospital): 手动记录病情

---

src/plugins/hospital/__init__.py
src/plugins/hospital/data_source.py
tests/plugins/hospital/test_history_admit.py
tests/plugins/hospital/test_record.py

通过 `/入院记录` 查看入院次数和每个人具体的入/出院时间。

feat(hospital): 支持查看入院记录

---

.github/workflows/main.yml

ci: 部署时添加 ssh port 设置

---

poetry.lock
pyproject.toml

词云插件现在支持 OneBot 12，Bison 现在支持多机器人。

feat: 更新词云，Bison 插件及其他依赖

---

.env
README.md
docker-compose.yml

调整 docker-compose 文件，添加了 walle-k 与 teydacore。

docs: 更新部署相关文档

---

src/plugins/ff14/plugins/fflogs/__init__.py
src/plugins/hospital/__init__.py
src/utils/helpers.py
tests/fake.py
tests/plugins/ban/test_ban.py
tests/plugins/ff14/test_fflogs.py
tests/plugins/ff14/test_gate.py
tests/plugins/ff14/test_nuannuan.py
tests/plugins/ff14/test_price.py
tests/plugins/hospital/test_admit.py
tests/plugins/hospital/test_discharge.py
tests/plugins/hospital/test_history_admit.py
tests/plugins/hospital/test_record.py
tests/plugins/hospital/test_rounds.py
tests/plugins/morning/test_hello.py
tests/plugins/morning/test_morning.py
tests/plugins/music/test_music.py
tests/plugins/pcr/test_calendar.py
tests/plugins/repeat/test_history.py
tests/plugins/repeat/test_rank.py
tests/plugins/repeat/test_repeat.py
tests/plugins/repeat/test_status.py
tests/plugins/robot/test_robot.py
tests/plugins/robot/test_tencent.py
tests/plugins/roll/test_rand.py
tests/plugins/roll/test_roll.py
tests/plugins/weather/test_eorzean.py
tests/plugins/weather/test_heweather.py

improve(helper): get_nickname 支持 ob12，并添加 get_mentioned_user 函数

---

.pre-commit-config.yaml
src/plugins/ff14/plugins/fflogs/__init__.py
src/plugins/ff14/plugins/fflogs/fflogs_api.py
src/plugins/ff14/plugins/fflogs/fflogs_data.py
src/plugins/ff14/plugins/fflogs/fflogs_models.py

fix(fflogs): 修复无法正确获取 adps 等类型输出的问题

---

Dockerfile

fix: 修复 playwright 无法安装的问题

---

CHANGELOG.md
poetry.lock
pyproject.toml
src/plugins/cyber_hospital/__init__.py
src/plugins/ff14/plugins/ff14_fflogs/__init__.py
tests/conftest.py

fix: 修复获取用户时的报错

---

.env
CHANGELOG.md

不然会被腾讯 WAF 拦截。
```html
<!DOCTYPE html><html><head><script>var i=location.href;var v=window.btoa?window.btoa(window.encodeURIComponent(i)):"";window.location.href="https://waf.tencent.com/501page.html?u="+location.origin+"&id=496c624222d88e88d1b89089b1805c16-1697081705294326-14325-140077704603392-29757519467789282&st=01&v="+v;</script></head></html>
```

fix(status): 状态插件默认不发送 Disk 数据

---

CHANGELOG.md
src/plugins/ff14/plugins/ff14_fflogs/__init__.py
src/utils/permission.py
tests/conftest.py
tests/plugins/ff14/test_fflogs.py

fix: 修复超级管理员权限判断问题

---

CHANGELOG.md
src/plugins/check_in/plugins/check_in_history.py
src/plugins/ff14/plugins/ff14_fflogs/__init__.py
tests/plugins/check_in/test_check_in_history.py
tests/plugins/ff14/test_fflogs.py

fix: 处理参数有多余的空格的情况

---

.env
CHANGELOG.md

必须要设置 SENTRY_INTEGRATIONS 才会触发 validator 添加 LoguruIntegration。

fix: 修复无法捕获 NoneBot 错误日志的问题

---

CHANGELOG.md
src/plugins/check_in/plugins/check_in_history.py
tests/plugins/check_in/test_check_in_history.py

fix(check_in): 修复打卡历史选项不直观的问题

---

.env
bot.py
poetry.lock
pyproject.toml

qqguild 适配器被 qq 适配器替代。
大别野将在 3 月 12 日下线。

remove: 移除 qqguild 和 villa 适配器

---

src/plugins/ff14/plugins/ff14_daily_quests/__init__.py
tests/plugins/ff14/test_daily_quests.py

improve(daily_quests): 记录每日委托之后直接显示与自己每日委托相同的群友

---

CHANGELOG.md
src/plugins/ff14/plugins/ff14_daily_quests/__init__.py
src/plugins/ff14/plugins/ff14_daily_quests/data_source.py
tests/plugins/ff14/test_daily_quests.py

improve(daily_quests): 优化每日委托的体验

---

src/plugins/ff14/plugins/ff14_daily_quests/__init__.py
src/plugins/ff14/plugins/ff14_daily_quests/data_source.py
tests/plugins/ff14/test_daily_quests.py

improve(daily_quests): 每日委托增加总览功能

---

poetry.lock
pyproject.toml

修复了 inherit_supported_adapters 的问题。

chore(deps): 更新 NoneBot 2.3.0

---

CHANGELOG.md
Dockerfile
docker-compose.yml
docker/gunicorn_conf.py
docker/start.sh

直接参考 tiangolo/uvicorn-gunicorn-docker 项目配置镜像。

docs: 直接使用 Python 官方镜像

---

CHANGELOG.md
src/plugins/qq_bot.py
tests/conftest.py
tests/plugins/test_qq_bot.py

feat: 支持 QQ 机器人平台的校验文件

---

pyproject.toml
requirements-dev.lock
tests/conftest.py
tests/plugins/ban/test_ban.py
tests/plugins/ff14/test_gate.py
tests/plugins/ff14/test_nuannuan.py
tests/plugins/ff14/test_price.py
tests/plugins/hospital/test_rounds.py
tests/plugins/morning/test_hello.py
tests/plugins/morning/test_morning.py
tests/plugins/music/test_music.py
tests/plugins/repeat/test_history.py
tests/plugins/repeat/test_rank.py
tests/plugins/repeat/test_repeat.py
tests/plugins/roll/test_rand.py
tests/plugins/roll/test_roll.py
tests/plugins/weather/test_eorzean.py
tests/plugins/weather/test_heweather.py

补全了很多缺失的 should_finished 和 should_rejected。

tests: 优化测试写法

---

.env
pyproject.toml
requirements-dev.lock
requirements.lock

- 现在需要浏览器才能订阅 B 站
- 修复 FF14 无法检查更新的问题

fix(bison): 修复插件订阅 B 站和最终幻想XIV 出错的问题

---

.env
CHANGELOG.md
pyproject.toml
requirements-dev.lock
requirements.lock

新版 memes 无法设置命令前缀，现在均统一用 / 触发。

feat(memes): 增加表情调用次数统计

---

CHANGELOG.md
src/plugins/check_in/__init__.py
src/plugins/cyber_hospital/__init__.py
src/plugins/ff14/__init__.py
src/plugins/morning/__init__.py
src/plugins/repeat/__init__.py

所有用到 nonebot_plugin_orm 的插件均需要手动 require。~~怎么感觉以前也修过~~

fix: 修复运行迁移脚本时加载插件报错

---

pyproject.toml
requirements-dev.lock
requirements.lock

nb2 现在将缓存 TypeAdapter 以优化依赖注入性能。

improve: 优化 nonebot2 的性能

---

.github/workflows/main.yml
Dockerfile
pyproject.toml

build: 使用 build-args 传递 VERSION 信息

---

CHANGELOG.md
src/plugins/ban/__init__.py
src/plugins/morning/__init__.py
src/plugins/music/__init__.py

fix: 再次修复运行迁移脚本时加载插件报错

---

tests/plugins/ban/conftest.py
tests/plugins/ban/test_ban.py
tests/plugins/ban/test_ban_group.py
tests/plugins/ban/test_ban_private.py
tests/plugins/check_in/test_body_fat.py
tests/plugins/check_in/test_check_in_history.py
tests/plugins/check_in/test_dietary.py
tests/plugins/check_in/test_fitness.py
tests/plugins/check_in/test_weight.py
tests/plugins/cyber_hospital/test_admit.py
tests/plugins/cyber_hospital/test_discharge.py
tests/plugins/cyber_hospital/test_history_admit.py
tests/plugins/cyber_hospital/test_record.py
tests/plugins/cyber_hospital/test_rounds.py
tests/plugins/ff14/test_daily_quests.py
tests/plugins/ff14/test_fflogs.py
tests/plugins/ff14/test_gate.py
tests/plugins/ff14/test_nuannuan.py
tests/plugins/ff14/test_price.py
tests/plugins/music/test_music.py
tests/plugins/repeat/test_history.py
tests/plugins/repeat/test_rank.py
tests/plugins/repeat/test_repeat.py
tests/plugins/roll/test_rand.py
tests/plugins/roll/test_roll.py
tests/plugins/weather/test_eorzean.py
tests/plugins/weather/test_heweather.py

以前仅针对单个响应器进行测试，有些并发问题没能发现，以后均针对所有响应器进行测试。

tests: 测试时针对所有响应器进行测试

---

.github/workflows/main.yml
.gitignore
pyproject.toml

ci: 上传测试结果至 Codecov

---

CHANGELOG.md
src/plugins/ff14/plugins/ff14_daily_quests/mogu.py
src/plugins/ff14/plugins/ff14_fflogs/data.py
src/plugins/morning/plugins/morning_greeting/data_source.py
tests/plugins/ff14/test_daily_quests.py
tests/plugins/ff14/test_fflogs.py
tests/plugins/morning/test_morning.py

feat: 使用 GitHub Pages 上的 json 文件

---

CHANGELOG.md
src/plugins/morning/plugins/hello/__init__.py
src/plugins/morning/plugins/morning_greeting/__init__.py

fix(morning): 修复普通用户可以开启问候的问题

---

pyproject.toml
uv.lock

bison 和 memes 所需的 pillow 版本冲突了

chore(deps): 升级 httpx 版本

---

.env
CHANGELOG.md
pyproject.toml
uv.lock

<https://github.com/KomoriDev/nonebot-plugin-deepseek>
使用 /ds 命令向 deepseek 提问。

feat: 添加 deepseek 插件

---

.env
CHANGELOG.md
pyproject.toml
uv.lock

feat: 新增 prometheus 插件

---

src/utils/permission.py

fix: 使用依赖注入的 User 来判断权限
